---
- name: Setup PostgreSQL master
  hosts: master
  become: yes
  tasks:
    - name: Stop existing PostgreSQL container if running
      docker_container:
        name: postgres_master
        state: absent

    - name: Remove existing data directory
      command: docker run --rm -v /var/lib/postgresql/data:/var/lib/postgresql/data busybox sh -c "rm -rf /var/lib/postgresql/data/*"

    - name: Pull PostgreSQL image
      docker_image:
        name: postgres
        tag: "12"
        source: pull

    - name: Create new data directory
      command: docker run --rm -v /var/lib/postgresql/data:/var/lib/postgresql/data busybox sh -c "mkdir -p /var/lib/postgresql/data && chown -R 999:999 /var/lib/postgresql/data"

    - name: Start PostgreSQL container
      docker_container:
        name: postgres_master
        image: postgres:12
        state: started
        restart_policy: always
        ports:
          - "5433:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        volumes:
          - /var/lib/postgresql/data:/var/lib/postgresql/data

    - name: Wait for PostgreSQL to start
      wait_for:
        port: 5433
        delay: 10

    - name: Create replication user
      command: docker exec -u postgres postgres_master psql -c "CREATE ROLE replicator WITH REPLICATION PASSWORD 'replicator_password' LOGIN;"

    - name: Configure PostgreSQL for replication
      template:
        src: roles/master/templates/postgresql.conf.j2
        dest: /var/lib/postgresql/data/postgresql.conf
      notify: Restart PostgreSQL container

    - name: Configure pg_hba.conf for replication
      template:
        src: roles/master/templates/pg_hba.conf.j2
        dest: /var/lib/postgresql/data/pg_hba.conf
      notify: Restart PostgreSQL container

  handlers:
    - name: Restart PostgreSQL container
      docker_container:
        name: postgres_master
        state: started
        restart: yes
